pipeline{
    agent any 
    stages{
        stage('Git Checkout'){
            steps{
               git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/test-1.git' 
            }
        }

        stage('Build'){
            steps{
                echo 'Building the project...'
            }
        }

    }
}