pipeline{
    agent {
        label 'prod'
    }

    stages{
        stage('server-ip'){
            steps{
                sh '''
                    hostname -I
                    echo "Server IP Address: $(hostname -I)"
                '''
            }
        }
        stage('Uptime'){
            steps{
                sh '''
                    uptime
                    echo "Server IP Address: $(uptime)"
                '''
            }

        }
    }

}